CREATE TABLE EMP_INFO
(LNAME varchar(50), 
FNAME varchar(50),
 ADDRESS varchar(50),
 POSITION varchar(50),
 SALARY int,
 AGE int
 );

INSERT INTO EMP_INFO (LNAME , FNAME ,ADDRESS , POSITION ,SALARY,AGE )
 VALUES ('ALFONSO', 'JUANITO', 'BACOOR,CAVITE','HEAD MANAGER', 35000,26),
('ROSWELL', 'EZEKIEL', 'MANILA,MANILA','ASSISTANT MANAGER', 30000,28),
('RORONOA', 'ZORO', 'PASAY,MANILA','SUPERVISOR', 28000,25),
('CRAIGE', 'ACE', 'KAWIT,CAVITE','ASSISTANT SUPERVISOR', 25000,27)
,('MONKEY', 'LUFFY', 'IMUS,CAVITE','TASK MANAGER', 28000,20);