SELECT SUM(PRICE*QUANTITY) AS BURGER_TOTALSALE
from RECEIPT
WHERE PRODUCT_NAME = 'BURGER';
SELECT SUM(PRICE*QUANTITY) AS FRIES_TOTALSALE
from RECEIPT
WHERE PRODUCT_NAME = 'FRIES';
SELECT SUM(PRICE*QUANTITY) AS MILKTEA_TOTALSALE
from RECEIPT
WHERE PRODUCT_NAME = 'MILKTEA';

