CREATE TABLE ORDER_RECEIPT
(
ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_NAME VARCHAR(30),
PRICE INT,
QUANTITY INT
);


INSERT INTO ORDER_RECEIPT(PRODUCT_NAME,PRICE,QUANTITY)
 VALUES
 ('SHAWARMA' ,60 ,23),
 ( 'TAKOYAKI' ,98,32),
 ('BURGER' , 35, 3),
 ( 'FRIES' , 40, 6),
 ( 'MILKTEA' , 70, 9),
 ( 'CORNDOG' , 48, 3);
 


 SELECT *,
 PRICE*QUANTITY AS total_price
FROM ORDER_RECEIPT; 